events {
    # Basic events block (required for NGINX to start)
    worker_connections 1024;
}
http {
    server {
        listen 80;

        # Route for SiteMain
        location /sitemain {
            #root /usr/share/nginx/html;         
            root /usr/share/nginx/html/sitemain/;
            index SiteMain.html;
        }

        # Route for Version1
        location /version1 {
           # root /usr/share/nginx/html;          
            root /usr/share/nginx/html/version1/;
            index Version1.html;
        }

        # Route for Version2
        location /version2 {
            #root /usr/share/nginx/html;           
            root /usr/share/nginx/html/version2/;
            index version2.html;
        }
    }
}